# Generated by Django 5.0.6 on 2024-12-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_room_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='currentSong',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
